// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  text_field: () =>
    import(
      /* webpackChunkName: "prismic__slicesform__text_field" */ "./TextField/index.vue"
    ),
};
