// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  form_field: () =>
    import(
      /* webpackChunkName: "prismic__slicesform__form_field" */ "./FormField/index.vue"
    ),
};
