// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  boxes: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__boxes" */ "./Boxes/index.vue"
    ),
  button_group: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__button_group" */ "./ButtonGroup/index.vue"
    ),
  cards: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__cards" */ "./Cards/index.vue"
    ),
  columns: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__columns" */ "./Columns/index.vue"
    ),
  gallery: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__gallery" */ "./Gallery/index.vue"
    ),
  slideshow: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__slideshow" */ "./Slideshow/index.vue"
    ),
  split: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__split" */ "./Split/index.vue"
    ),
  text_block: () =>
    import(
      /* webpackChunkName: "prismic__slicespage__text_block" */ "./TextBlock/index.vue"
    ),
};
