// Code generated by Slice Machine. DO NOT EDIT.

export const components = {
  navigation: () =>
    import(
      /* webpackChunkName: "prismic__slicesfooter__navigation" */ "./Navigation/index.vue"
    ),
  opening_hours: () =>
    import(
      /* webpackChunkName: "prismic__slicesfooter__opening_hours" */ "./OpeningHours/index.vue"
    ),
};
